name: test foo

on:
  push:
  pull_request:


env:
  REGISTRY: ghcr.io

concurrency:
  group: ${{ github.workflow }}-${{ github.event.pull_request.number || github.run_id }}
  cancel-in-progress: true

jobs:
  build:
    env:
      RUNC_CMD: podman
      OS_IMAGE: "fedora:36"
      # https://github.com/actions/runner-images/issues/6282
      XDG_RUNTIME_DIR: ''

    name: Build ovn-fake-multinode image
    runs-on: ubuntu-20.04
    steps:
    - name: Check out ovn-fake-multi-node
      uses: actions/checkout@v3
      with:
        repository: 'ovn-org/ovn-fake-multinode'
        path: 'ovn-fake-multinode'
        ref: 'v0.1'
