name: Build and Test

on:
  push:
  pull_request:
  schedule:
    # Run Sunday at midnight
    - cron: '0 0 * * 0'

concurrency:
  group: ${{ github.workflow }}-${{ github.event.pull_request.number || github.run_id }}
  cancel-in-progress: true

jobs:
  build-osx:
    env:
      CC:    clang
      OPTS:  --disable-ssl

    name:    osx clang --disable-ssl
    runs-on: macos-latest

    strategy:
      fail-fast: false

    steps:
    - name: checkout
      if: github.event_name == 'push' || github.event_name == 'pull_request'
      uses: actions/checkout@v4
      with:
        submodules: recursive
    # For weekly runs, don't update submodules
    - name: checkout without submodule
      if: github.event_name == 'schedule'
      uses: actions/checkout@v4
    # Weekly runs test using the tip of the most recent stable OVS branch
    # instead of the submodule.
    - name: checkout OVS
      if: github.event_name == 'schedule'
      uses: actions/checkout@v4
      with:
        repository: 'openvswitch/ovs'
        fetch-depth: 0
        path: 'ovs'
    - name: checkout OVS most recent stable branch.
      if: github.event_name == 'schedule'
      run: |
        git checkout \
          $(git branch -a -l '*branch-*' | sed 's/remotes\/origin\///' | \
            sort -V | tail -1)
      working-directory: ovs
    - name: install dependencies
      run:  brew install automake libtool
    - name: update PATH
      run:  |
        echo "$HOME/bin"        >> $GITHUB_PATH
        echo "$HOME/.local/bin" >> $GITHUB_PATH
    - name: set up python
      uses: actions/setup-python@v5
      with:
        python-version: '3.12'
    - name: prepare
      run:  ./.ci/osx-prepare.sh
    - name: build
      run:  ./.ci/osx-build.sh
    - name: upload logs on failure
      if: failure()
      uses: actions/upload-artifact@v4
      with:
        name: logs-osx-clang---disable-ssl
        path: config.log
